### ISSUE TITLE
Problema con el autocompletado

### ISSUE THREAD

**Issue by Jeannix** [oscaramos/caratulas-ucsp#3]
Intenté hacer una carátula con el curso de Historia de la cultura y no se mostró.

![test](https://user-images.githubusercontent.com/23278614/112857793-d2ac9b00-9076-11eb-9af2-9987c41b98bf.png)
![test2](https://user-images.githubusercontent.com/23278614/112857795-d3453180-9076-11eb-92e8-51a4c37909e2.png)

**Comment by oscaramos** [comment]
Muchisimas gracias por informar sobre este problema.
